/*
console.log("hello this is an Array");

var a = new Array();
console.log(a);

var a = [1234, "santhu", false, null];
console.log(a[4,0]);
console.log(a);
console.log(typeof a[2]);
console.log(typeof a);
a.push("adding");
console.log(a);

var a = 10 + "10" - 5;

alert(a);
*/

alert("Array Approach in Java Script");
//var n=promt("please enter the n value");

var a=[10,"AAA",false,true,"100",["BBB",200,false]];
console.log(a[0]);
console.log(a[5][1]);
console.log(a);
console.log(typeof a);
